services:
  app:
    image: frafra/is-osm-uptodate
    build: .
    profiles:
      - prod
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    ports:
      - 8000:8000
  app-dev:
    build: .
    command: ["pdm", "run", "flask", "run", "--host=0.0.0.0", "--port=8000"]
    profiles:
      - dev
    depends_on:
      - redis-dev
    environment:
      REDIS_HOST: redis-dev
      FLASK_APP: is-osm-uptodate.py
      FLASK_DEBUG: 1
      FLASK_ENV: development
    volumes:
      - ./is-osm-uptodate.py:/home/app/is-osm-uptodate.py:ro
      - ./conf/uwsgi.ini:/home/app/conf/uwsgi.ini:ro
      - ./web:/home/app/web:ro
    ports:
      - 8000:8000
  app-test:
    build: .
    profiles:
      - test
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
  app-dev-frontend:
    build:
      dockerfile: Dockerfile
      target: builder
    command: ["npm", "run", "develop"]
    profiles:
      - dev
    depends_on:
      - app-dev
    environment:
      BACKEND_URL: http://app-dev:8000
    volumes:
      - ./web:/home/app/web
    ports:
      - 8080:8080
  redis:
    build: redis
    profiles:
      - prod
      - test
  redis-dev:
    build: redis
    profiles:
      - dev
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    profiles:
      - test
    depends_on:
      - app-test
    environment:
      URL: "http://app-test:8000"
    volumes:
      - ./latest_logs/:/home/app/latest_logs/
