services:
  app:
    image: ghcr.io/frafra/is-osm-uptodate:master
    build:
      context: .
      args:
        SENTRY_DSN: "https://272ecef41e6748cc8b2e955f3a23d67a@o1253953.ingest.sentry.io/6421667"
    profiles:
      - prod
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      GUNICORN_CMD_ARGS: "--workers 2"
    ports:
      - 8000:8000
  app-dev:
    build: .
    profiles:
      - dev
    depends_on:
      - redis-dev
    environment:
      REDIS_HOST: redis-dev
      GUNICORN_CMD_ARGS: "--reload --log-level debug"
    volumes:
      - ./server:/app/server:ro
      - ./web:/app/web:ro
    ports:
      - 8000:8000
  app-test:
    build: .
    profiles:
      - test
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      GUNICORN_CMD_ARGS: "--log-level debug"
  app-dev-frontend:
    build:
      dockerfile: Dockerfile
      target: builder
    command: ["npm", "run", "develop"]
    profiles:
      - dev
    depends_on:
      - app-dev
    environment:
      BACKEND_URL: http://app-dev:8000
    volumes:
      - ./web:/app/web
    ports:
      - 8080:8080
  redis:
    build: redis
    profiles:
      - prod
      - test
  redis-dev:
    build: redis
    profiles:
      - dev
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    profiles:
      - test
    depends_on:
      - app-test
    environment:
      URL: "http://app-test:8000"
    volumes:
      - ./latest_logs/:/app/latest_logs/
