app = "is-osm-uptodate"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  REDIS_HOST = "is-osm-uptodate-redis.internal"
  GUNICORN_CMD_ARGS = "--workers 2"

[build.args]
  SENTRY_DSN = "https://272ecef41e6748cc8b2e955f3a23d67a@o1253953.ingest.sentry.io/6421667"

[[statics]]
  guest_path = "/app/web/dist/"
  url_prefix = "/"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "5s"
