[tool.poetry]
name = "is-osm-uptodate"
version = "1.6"
description = "Find outdated nodes in OpenStreetMap"
authors = ["Francesco Frassinelli <fraph24@gmail.com>"]
license = "AGPLv3"

[tool.pdm]
includes = []
[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[project]
name = "is-osm-uptodate"
version = "1.6"
description = "Find outdated nodes in OpenStreetMap"
authors = [
    {name = "Francesco Frassinelli", email = "fraph24@gmail.com"},
]
dependencies = [
    "Flask<3.0.0,>=2.0.1",
    "jsonslicer<1.0.0,>=0.1.7",
    "simplejson<4.0.0,>=3.17.2",
    "uWSGI<3.0.0,>=2.0.19",
]
requires-python = ">=3.8,<4.0"
dynamic = ["classifiers"]
license = {text = "AGPLv3"}

[project.optional-dependencies]

[tool.pdm.dev-dependencies]
dev = [
    "pre-commit<3.0.0,>=2.13.0",
    "black<22.0,>=21.6b0",
    "flakehell<1.0.0,>=0.9.0",
    "isort<6.0.0,>=5.9.1",
]
test = [
    "seleniumbase~=1.63",
]

[tool.pdm.scripts]
npm = {shell = "cd web && npm ci"}
web = "uwsgi --ini uwsgi.ini"
docker = "./scripts/run_docker.sh"
test = "pytest --browser=firefox --save_screenshot tests/"
test_docker = "./scripts/run_tests.sh"
lint = "pre-commit run --all-files"

[tool.flakehell]
# https://flakehell.readthedocs.io/
# https://black.readthedocs.io/en/stable/compatible_configs.html?highlight=flake8#flake8
max-line-length = 88
extend-ignore = "E203, W503"
# https://github.com/flakehell/flakehell/issues/10#issuecomment-822720074
extended_default_ignore = []  # add this

[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/black_compatibility/
profile = "black"

[project.urls]

