version: 2
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - run:
          name: Install Docker Compose
          command: |
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            apk add --no-cache curl git docker-cli
            curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
            chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: Build containers
          command: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker compose --profile test build
      - run: docker compose --profile test run test
      - store_artifacts:
          path: latest_logs
