version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker build --target=tester -t tester .
      - run: docker run --name=tester tester
      - run: docker cp tester:/home/app/tests/latest_logs
      - store_artifacts:
          path: latest_logs
