services:
  app:
    image: frafra/is-osm-uptodate
    profiles:
      - stable
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    ports:
      - 8000:8000
  app-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    profiles:
      - dev
      - test
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    ports:
      - 8000:8000
  redis:
    image: docker.io/library/redis:6
  test:
    build:
      context: ..
      dockerfile: tests/Dockerfile
    profiles:
      - test
    depends_on:
      - app-dev
    environment:
      URL: "http://app-dev:8000"
    volumes:
      - ./latest_logs/:/home/app/latest_logs/
