# fly.toml file generated for is-osm-uptodate-redis on 2022-05-11T19:29:49+02:00

app = "is-osm-uptodate-redis-test"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

# example: flyctl volumes create redis_data --no-encryption -r fra -s 1
#[mounts]
#source = "redis_data"
#destination = "/data"

[[services]]
  http_checks = []
  internal_port = 6379
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 64
    soft_limit = 32
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
